/**
 * Copy pdf.js UMD build and emit inline TS modules for WebView (no ExpoAsset.downloadAsync).
 * Run automatically via npm postinstall.
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "node_modules", "pdfjs-dist", "build", "pdf.min.js");
const workerSrc = join(root, "node_modules", "pdfjs-dist", "build", "pdf.worker.min.js");
const destDir = join(root, "assets", "pdfjs");
const destBundle = join(destDir, "pdf.min.bundle");
const destInline = join(root, "src", "lib", "pdfJsInline.ts");

if (!existsSync(src) || !existsSync(workerSrc)) {
  console.warn("embed-pdfjs: pdfjs-dist not installed yet — skipping");
  process.exit(0);
}

mkdirSync(destDir, { recursive: true });
copyFileSync(src, destBundle);

const raw = readFileSync(src, "utf8");
const workerB64 = readFileSync(workerSrc).toString("base64");
const ts = `/** Auto-generated by scripts/embed-pdfjs.mjs — do not edit. */
export const PDF_JS_INLINE: string = ${JSON.stringify(raw)};
export const PDF_JS_WORKER_B64: string = ${JSON.stringify(workerB64)};
`;
writeFileSync(destInline, ts, "utf8");

console.log(`embed-pdfjs: copied ${src} → ${destBundle}`);
console.log(`embed-pdfjs: wrote inline module → ${destInline}`);
